<div class="thrv_wrapper thrv-page-section" data-tve-style="1">
<div class="tve-page-section-out"></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-15d8a2fa7fb"><div class="thrv_wrapper thrv-columns" data-css="tve-u-15d8a548e9d"><div class="tcb-flex-row tcb-resized tcb-medium-wrap tcb-reverse tcb--cols--2"><div class="tcb-flex-col" data-css="tve-u-15d8a302b96"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper tve_image_caption tcb-mobile-hidden tcb-tablet-hidden" data-css="tve-u-15d8a301999"><span class="tve_image_frame"><img class="tve_image" alt="" srcset="{tcb_lp_base_url}/css/images/mini-squeeze2-product-150x150.png 150w, {tcb_lp_base_url}/css/images/mini-squeeze2-product-194x300.png 194w, {tcb_lp_base_url}/css/images/mini-squeeze2-product.png 336w" sizes="(max-width:336px) 100vw, 336px" width="336" height="520" title="mini-squeeze2-product" data-id="295" src="{tcb_lp_base_url}/css/images/mini-squeeze2-product.png"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-15d8a302bab"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15d8a4ee889">
<div class="tve-content-box-background" data-css="tve-u-15d8a2e867d"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15d8a2edfa4">
<div class="tve-content-box-background" data-css="tve-u-15d8a48cb07"></div>
<div class="tve-cb tve_empty_dropzone"><div class="thrv_wrapper thrv_heading"><h1 data-css="tve-u-15d8a3196ca" style="text-align: center;"><strong>You Have Successfully Signed Up!</strong></h1></div><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15da25eb61a"><span class="tve_image_frame"><img class="tve_image" alt="" srcset="{tcb_lp_base_url}/css/images/mini-squeeze2-download-150x127.png 150w, {tcb_lp_base_url}/css/images/mini-squeeze2-download.png 153w" sizes="(max-width:153px) 100vw, 153px" width="153" height="127" title="mini-squeeze2-download" data-id="294" src="{tcb_lp_base_url}/css/images/mini-squeeze2-download.png"></span></div></div>
</div><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" data-css="tve-u-15d8a5540d0">
<div class="tve-content-box-background" data-css="tve-u-15d8a555fdf" data-clip-id="ae0802ac8737d"><svg width="0" height="0" class="tve-decoration-svg"><defs><clipPath id="clip-top-ae0802ac8737d" class="decoration-clip clip-path-top" clipPathUnits="objectBoundingBox" decoration-type="none" pointer-width="37" pointer-height="100" clip-path="url(#clip-bottom-ae0802ac8737d)"><polygon points="0 0, 0 1, 1 1, 1 0"></polygon></clipPath><clipPath id="clip-bottom-ae0802ac8737d" class="decoration-clip clip-path-bottom" clipPathUnits="objectBoundingBox" decoration-type="pointer" slanted-angle="5" style="" pointer-width="42" pointer-height="100"><polygon points="0 0, 0 0, 0.29000000000000004 0, 0.5 1, 0.71 0, 1 0, 1 0"></polygon></clipPath></defs></svg></div>
<div class="tve-cb tve_empty_dropzone"></div>
</div><div class="thrv_wrapper thrv_text_element" data-css="tve-u-15da2602d9a"><p style="text-align: center;" data-css="tve-u-15da25ff2b4"><strong>Click the button</strong> to begin your download:</p></div><div class="thrv_wrapper thrv-button" data-css="tve-u-15da260d627">
<a href="" class="tcb-button-link" data-css="tve-u-15da262f68d">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-15da26278dd"><span style="color: rgb(255, 255, 255);"><span style="font-family: &quot;Open Sans&quot;; font-weight: 400; font-size: 36px;"><strong>Download Your Report</strong></span></span></span></span>
</a>
</div></div>
</div></div></div></div></div></div>
</div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-15d8a53f223"><p style="text-align: center;"><span style="font-size: 16px; color: rgb(255, 255, 255);">© Thrive Landing Pages. All rights Reserved | </span><a href="#"><span style="font-size: 16px; color: rgb(255, 255, 255);">Privacy Policy</span></a><span style="font-size: 16px; color: rgb(255, 255, 255);"> | Disclaimer</span></p></div>