<div class="thrv_wrapper thrv-page-section" data-css="tve-u-15dbc6b6c04">
<div class="tve-page-section-out" data-css="tve-u-15dbc71e92d"></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-15dc21dff60"><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15dbc68b05d"><span class="tve_image_frame"><a href="http://landingpages.thrive-dev.bitstoneint.com/vision""><img class="tve_image" alt="" srcset="{tcb_lp_base_url}/css/images/video-lead-logo.png 132w" sizes="(max-width:132px) 100vw, 132px" width="132" height="27" title="video-lead-logo" data-id="400" src="{tcb_lp_base_url}/css/images/video-lead-logo.png" data-link-wrap="1"></a></span></div></div>
</div><div class="thrv_wrapper thrv-page-section" data-css="tve-u-15dbc759f64" style="">
<div class="tve-page-section-out" data-css="tve-u-15dbc6d5882"></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-15dbc709691"><div class="thrv_wrapper thrv_heading" data-css="tve-u-15dbc7565af" style=""><h1 data-css="tve-u-15dc07ed053" style="text-align: center;">"Discover the&nbsp;<strong><span style="color: rgb(255, 208, 44);">Easiest</span></strong>
<strong><span style="color: rgb(255, 208, 44);">Way</span></strong>&nbsp;to Create Flexible, High-Conversion Landing Pages... and&nbsp;<strong><span style="color: rgb(255, 208, 44);">Get More Leads</span></strong>&nbsp;than Ever!"</h1></div><div class="thrv_wrapper thrv-columns" data-css="tve-u-15dc0731012"><div class="tcb-flex-row tcb--cols--2 tcb-medium-wrap" data-css="tve-u-15dc0add82d"><div class="tcb-flex-col c-66"><div class="tcb-col tve_empty_dropzone"><div class="thrv_responsive_video thrv_wrapper" data-type="youtube" data-url="https://www.youtube.com/watch?v=GFKqKQPQ5Ws" data-css="tve-u-15dbd39ffdd" data-showinfo="0" style="">
<div class="tve_responsive_video_container">
<div class="video_overlay"></div>
<iframe data-code="GFKqKQPQ5Ws" data-provider="youtube" src="https://www.youtube.com/embed/GFKqKQPQ5Ws?rel=1&amp;modestbranding=0&amp;controls=1&amp;showinfo=0&amp;fs=1&amp;wmode=transparent" data-src="https://www.youtube.com/embed/GFKqKQPQ5Ws?rel=1&amp;modestbranding=0&amp;controls=1&amp;showinfo=0&amp;fs=1&amp;wmode=transparent" frameborder="0" allowfullscreen=""></iframe></div>
</div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15e0eed214a"><p data-css="tve-u-15dc07fddee" style="text-align: center;"><em>Watch the video to see how this report will change the way you build landing pages.</em></p></div></div></div><div class="tcb-flex-col c-33"><div class="tcb-col tve_empty_dropzone"><div class="thrv_wrapper thrv_heading" data-css="tve-u-15dbc8fa4b8"><h3 data-css="tve-u-15dbd2febef" style="text-align: center;"><strong>Download Your Free Report:</strong></h3></div><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15dbc8d5bcf"><span class="tve_image_frame" style="width: 100%;"><img class="tve_image" alt="" srcset="{tcb_lp_base_url}/css/images/vibrant_lead_product-150x150.png 150w, {tcb_lp_base_url}/css/images/vibrant_lead_product-250x300.png 250w" sizes="(max-width:250px) 100vw, 250px" width="250" height="300" title="vibrant_lead_product" data-id="374" src="{tcb_lp_base_url}/css/images/vibrant_lead_product-250x300.png" style="width: 100%;"></span></div><div class="thrv_wrapper thrv-button tve_ea_thrive_lightbox" data-css="tve-u-15dbd3ff2c9">
<a href="#" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="__TCB_EVENT_[{&quot;config&quot;:{&quot;l_anim&quot;:&quot;instant&quot;,&quot;l_id&quot;:&quot;5166&quot;},&quot;a&quot;:&quot;thrive_lightbox&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-15dbd432e10"><span style="font-family: Roboto; font-weight: 300;"><strong><span style="font-size: 24px;">Get the Free Report »</span></strong></span></span></span>
</a>
</div></div></div></div></div><div class="thrv_wrapper thrv-divider" data-style="tve_sep-1" data-thickness="1" data-color="rgb(255, 255, 255)" data-css="tve-u-15dc0725d8d">
<hr class="tve_sep tve_sep-1">
</div></div>
</div><div class="thrv_wrapper thrv-page-section" data-css="tve-u-15dc0869997">
<div class="tve-page-section-out" data-css="tve-u-15dbc6d5882"></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-15dc086a809"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" data-css="tve-u-15dc0a2c179"><p style="text-align: center;">© {tcb_current_year} by ACME Inc.</p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone"><p style="text-align: center;"><a href="http://landingpages.thrive-dev.bitstoneint.com/vision/"><span style="color: rgb(255, 255, 255);"><u>Disclaimer</u></span></a></p></div></div>
</div>